#!/bin/sh
#PBS -S /bin/sh
#PBS -N anvi_mapping_metahit
#PBS -A earth523w17_fluxm
#PBS -l qos=flux
#PBS -q fluxm
#PBS -l nodes=1:ppn=4
#PBS -l walltime=48:00:00
#PBS -l mem=100gb
#PBS -m abe
#PBS -j oe
#PBS -V
#
#
echo "I ran on:"
cat $PBS_NODEFILE

cd /scratch/earth523w17_fluxm/emcrosse/Anvio_Manure/

## Make sure you load the following modules before submitting the scripts
# module load bedtools/2.22.1
# module load geomicro/bwa/0.7.10
# module load geomicro/samtools/1.0

## Run this script in your /scratch/earth523w17_fluxm/$USERNAME/EARTH523/ directory
## The referenced directory (Mapping) contains a fwd.fastq, rev.fastq and reference fasta
## If you have multiple *fwd.fastq and *rev.fastq for your sample, concatenate them
## The reference fasta must be named scaffold.fasta
## If you have multiple samples to map to a reference, submit this script for each sample
## changing out the contents of Mapping, or changing the directory in this script
## Edit the path name to reflect location of mapping.

perl /scratch/earth523w17_fluxm/emcrosse/Anvio_Manure/mapping.sh Sample77309

