#!/bin/sh
#PBS -N megaHIT_523
#PBS -V
#PBS -A earth523w17_fluxm
#PBS -l qos=flux
#PBS -q fluxm
#PBS -l nodes=4:ppn=4
#PBS -l walltime=24:00:00
#PBS -l mem=400gb
#PBS -M eamuelle@umich.edu
#PBS -m abe
#PBS -j oe

#load module
#module load megahit/1.0.6

#give access to folder
echo "I ran on:"
cat $PBS_NODEFILE
cd $PBS_O_WORKDIR

cd /scratch/earth523w17_fluxm/eamuelle/MegaHIT/
#code
megahit --12 int_77309_77310_77311.fasta -o ./Megahit_3_29_17_2
