#!/bin/sh
#PBS -N QUAST_Megahit
#PBS -V
#PBS -A earth523w17_fluxm
#PBS -l qos=flux
#PBS -q fluxm
#PBS -l nodes=4:ppn=4
#PBS -l walltime=24:00:00
#PBS -l mem=400gb
#PBS -M eamuelle@umich.edu
#PBS -m abe
#PBS -j oe

echo "I ran on:"
cat $PBS_NODEFILE
cd $PBS_O_WORKDIR

cd /scratch/earth523w17_fluxm/eamuelle/MegaHIT/Megahit_3_29_17_2/

#list of modules to load
#module load python-anaconda2 boost/1.61.0
#module load quast/4.3

metaquast.py ./final.contigs.fa -o ./QUAST/
